#!/bin/sh
#

w=""
wans="["
for n in $(uci show network | grep wan | awk -F'[/=.]' '{print $2}' | sort -u)
do
	w=$w" "$n
done
for n in $(echo $w)
do
        if [[ $n != *"_dev"* ]]; then
                wans=$wans"{\"{#WAN}\":\"$n\"},"
        fi
done
echo "${wans:: -1}]"
exit 0
